language: go

go:
  - 1.7.x
  - 1.8.x
  - master
env:
  - secure: "kwYpKk2kS/Pa2mvf3U0t85eGT90kdyglOgBmdxghLVgOZulPP6lJx52Od/t0q4M6kh/4SbWELg0b74zQ4viQyPCXPiYhfxgAVaW/jntSU8m7LPv3MfxZk31BnD4B4+08qj9BVLBrGb98/r4ZrnOO6Bh/pjLjQb94lZUKkocTZlfgmMPyQI7A3G+ALdujmVSWuFNJSw/bQcpQ4kJAiuUXmDt/UOJXCPyr73Vun88JB4+Wd2EPf6HNtefb+bzJqlc7lbxBHzgvnVKEdVi3vyV+hHx196qzmLrhi27dqRV3f/drLPaOiDU3ig0y8xcL+kIaM6SSaXB96oGCD/G0iWVLmyzry5G6tB9ExCqSmPtWKgZNKzslgh/WPfh5kdvwhQzX+jniVDLwUq+8Men0tmAu5v70RPEd7F0joaZ2G7iOMazNhsOqVXyPr6YxtMA8woS6hkCyiPWGlPl+wN7tFz6ovCqLF3xwy1Tz/N8VOzaZKLwJjXWDmzqFOODoQgLBzbabrjYNBFyjbgkQkU+NFn11KOTjPAxMUE7UIjbYnoRRQWRLM61D4vtJYrLxw2vUUpCQArAOuSdD0QT0H09qGpJBWICSMQ3p7ENZfBeTtwrtS3M2zPwP/eClexDG5EdnGD5Xqrx2gqwooO/Ve8+I4XLWInlJiALtSbsFvTwt8dDthOA="
install:
  - go get github.com/mattn/goveralls
script: CGO_ENABLED=0 go test -v ./... -bench=. -benchmem -covermode=atomic -coverprofile=coverage.out
after_script: goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
sudo: false
matrix:
  allow_failures:
    - go: master
